/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import CodeHelpers.ConexionesDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class PanelMenu extends javax.swing.JPanel {

ConexionesDB conector= new ConexionesDB();

String nombrePlatillo="";
String descripcionPlatillo="";
Float precioPlatillo=0.0f;
ResultSet resultadoConsulta;
ArrayList array;
DefaultListModel modelo;

    public PanelMenu() {
        initComponents();
        array= new ArrayList();
        modelo = new DefaultListModel();
        listaProductos.setModel(modelo);
        consultaGeneralPlatillos();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new CustomSwingObjects.CustomJButtonS();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new CustomSwingObjects.CustomJButtonS();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Listado de Productos");

        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setResizeWeight(0.9);

        listaProductos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaProductosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaProductos);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Información");

        btnEditar.setText("Nuevo");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        jLabel5.setText("Precio");

        txtPrecio.setEditable(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombre)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(txtPrecio)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    changeStatus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        

              registrarPlatillo();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void listaProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaProductosValueChanged
       String itemSeleccionado[]=listaProductos.getSelectedValue().split(" ");
       String idSeleccionado=itemSeleccionado[0];
        consultaEspecificaPlatillos(idSeleccionado);
    }//GEN-LAST:event_listaProductosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomSwingObjects.CustomJButtonS btnEditar;
    private CustomSwingObjects.CustomJButtonS btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
public void changeStatus()
{
    if(txtNombre.isEditable())
    {
        txtNombre.setEditable(false);
    }
    else{
        txtNombre.setEditable(true);
    }
    if(txtDescripcion.isEditable())
    {
        txtDescripcion.setEditable(false);
    }
    else{
        txtDescripcion.setEditable(true);
    }
    if(txtPrecio.isEditable())
    {
        txtPrecio.setEditable(false);
    }
    else{
        txtPrecio.setEditable(true);
    }
    if(txtNombre.isEditable())
    {
         btnEditar.setText("Cancelar");
         btnGuardar.setEnabled(true);

    }
    else
    {
         btnEditar.setText("Nuevo");
         txtNombre.setText("");
         txtDescripcion.setText("");
         txtPrecio.setText("");
         btnGuardar.setEnabled(false);
    }
}


public void registrarPlatillo()
{
   if(txtNombre.getText().equals(""))
   {
       JOptionPane.showMessageDialog(null, "El campo nombre no puede estar vacio");
   }
   else if(txtDescripcion.getText().equals(""))
   {
       JOptionPane.showMessageDialog(null, "El campo descripción no puede estar vacio");
   }
   else if(txtPrecio.getText().equals(""))
   {
       
        JOptionPane.showMessageDialog(null, "El campo precio no puede estar vacio");

   }
   else
   {
       nombrePlatillo=txtNombre.getText();
       descripcionPlatillo=txtDescripcion.getText();
       try{
            precioPlatillo=Float.parseFloat(txtPrecio.getText());
            String salida=conector.registrar("call registroPlatillo('"+nombrePlatillo+"','"+descripcionPlatillo+"',"+precioPlatillo+");");
            JOptionPane.showMessageDialog(null, salida);
            txtDescripcion.setText("");
            txtNombre.setText("");
            txtPrecio.setText("");

       }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "El campo precio no tiene un valor numerico");
       }
   }

}


public void consultaGeneralPlatillos()
{
    resultadoConsulta=conector.consulta("select * from Platillos;");
    modelo.removeAllElements();
    try {
        while(resultadoConsulta.next())
        {
            
            System.out.println(resultadoConsulta.getString("nombrePlatillo"));
            array.add(resultadoConsulta.getString("idPlatillo")+" "+resultadoConsulta.getString("nombrePlatillo"));
             
        }
        for (int i = 0; i < array.size(); i++) {
                modelo.addElement(array.get(i));
             }
       listaProductos.setSelectedIndex(0);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error al cargar el menu");
    }
}


public void consultaEspecificaPlatillos(String idPLatillo)
{
    resultadoConsulta=conector.consulta("select * from Platillos where idPlatillo="+idPLatillo+";");
    try {
        while(resultadoConsulta.next())
        {
            txtNombre.setText(resultadoConsulta.getString("nombrePlatillo"));
            txtDescripcion.setText(resultadoConsulta.getString("descripcion"));
            txtPrecio.setText(resultadoConsulta.getString("precioPlatillo"));
             
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error al cargar el menu");
    }
}


}
